# Generated by Django 3.2.8 on 2021-11-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event name')),
                ('from_date', models.DateTimeField(verbose_name='Event start')),
                ('to_date', models.DateTimeField(verbose_name='Event end')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='Comment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Event creator')),
            ],
        ),
    ]
